apiVersion: apps/v1
kind: Deployment
metadata: 
  name: db-deploy
  labels:
    name: db-deploy
    app: voting-app
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-pod
      app: voting-app
      tier: backend
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        app: voting-app
        tier: backend

    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"