apiVersion: apps/v1
kind: Deployment
metadata: 
  name: worker-app-deploy
  labels:
    name: worker-app-deploy
    app: voting-app
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker-app-pod
      app: voting-app
      tier: backend
  template:
    metadata:
      name: worker-app-pod
      labels:
        name: worker-app-pod
        app: voting-app
        tier: backend

    spec:
      containers:
      - name: worker-app
        image: kodekloud/examplevotingapp_worker:v1
    
    

    
  